# Generated by Django 5.1.1 on 2024-12-08 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='available_from',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='table',
            name='available_to',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
    ]
